/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author julio
 */
public class DialogoIrArchivo extends javax.swing.JDialog {

    Principal parent;

    /**
     * Creates new form DialogoIrArchivo
     *
     * @param parent
     * @param archivos
     */
    public DialogoIrArchivo(Principal parent, Vector<Archivo> archivos) {
        super(parent, true);
        this.parent = parent;
        initComponents();
        initList(archivos);
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    private void initList(Vector<Archivo> archivos) {
        if (archivos != null) {
            DefaultListModel<String> model = new DefaultListModel();
            for (int i = 0; i < archivos.size(); i++) {
                model.addElement(archivos.get(i).getName());
            }
            this.jListArchivos.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLienzo = new javax.swing.JPanel();
        jPanelCentro = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLienzo.setLayout(new java.awt.BorderLayout());

        jPanelCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitulo.setText("Seleccione el archivo al que desea navegar.");
        jPanelCentro.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jScrollPane1.setViewportView(jListArchivos);

        jPanelCentro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 170));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelCentro.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelCentro.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jPanelLienzo.add(jPanelCentro, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelLienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 579, 341));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        int sel = this.jListArchivos.getSelectedIndex();
        if (sel != -1) {
            this.parent.setActive(sel);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListArchivos;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelLienzo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
